In [ ]:
#Library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn.linear_model as lm
from sklearn.model_selection import train_test_split

In [ ]:
link='https://drive.google.com/file/d/1aVIPePUBUWzrbIW-3PAjLw5jh--F_fdH/view'
path = 'https://drive.google.com/uc?export=download&id='+link.split('/')[-2]
df = pd.read_csv(path)

In [ ]:
df.head(1)

No.  Profit  RnD  Adm  Marketing
0    1     192  165  137        472

In [ ]:
#X là feature còn Y là target
X=np.array([df.RnD.values,df.Adm.values,df.Marketing.values]).T
Y=np.array(df.Profit.values)

In [ ]:
#Chia bộ dữ liệu thành bộ dữ liệu huấn luyện và bộ dữ liệu kiểm tra
#Tập huấn luyện sẽ được sử dụng để huấn luyện mô hình, còn tập kiểm tra sẽ được sử dụng để đánh giá hiệu suất của mô hình trên dữ liệu mới.
#Việc chia dữ liệu thành hai tập là rất quan trọng để đánh giá hiệu suất của mô hình một cách chính xác. Nếu chúng ta chỉ sử dụng tập dữ liệu huấn luyện để đánh giá mô hình, thì mô hình có thể sẽ bị quá khớp (overfitting), nghĩa là mô hình sẽ chỉ hoạt động tốt trên tập dữ liệu huấn luyện và sẽ hoạt động kém trên dữ liệu mới.
#Việc sử dụng tập kiểm tra sẽ giúp chúng ta đánh giá hiệu suất của mô hình trên dữ liệu mới, từ đó có thể điều chỉnh mô hình cho phù hợp.
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [ ]:
model=lm.LinearRegression()

In [ ]:
model.fit(X_train,Y_train)
#Phương thức model.fit() trong Keras được sử dụng để huấn luyện mô hình. Phương thức này sẽ sử dụng tập dữ liệu huấn luyện X_train và Y_train để cập nhật các tham số của mô hình, nhằm giảm thiểu hàm mất mát (loss function) được chỉ định

In [ ]:
a=model.coef_
print(a)

[ 0.83401733 -0.13186696  0.00898828]


In [ ]:
b=model.intercept_
print(b)

64.97929172823731


In [ ]:
Y_pred=model.predict(X_test)
#Dự đoán thì nên dựa vào bộ train hay bộ test?

In [ ]:
from sklearn.metrics import r2_score,mean_squared_error
mse=mean_squared_error(Y_test,Y_pred)
r2_score=r2_score(Y_test,Y_pred)
print(r2_score)
print(mse)
#MSE: MSE cho biết trung bình một giá trị dự đoán lệch khỏi giá trị thực tế bao nhiêu. Giá trị MSE càng nhỏ thì mô hình càng tốt trong việc dự đoán các giá trị thực tế.
#R2 score: R2 score cho biết mô hình có thể giải thích được bao nhiêu biến thiên của dữ liệu đầu ra. Giá trị R2 score càng cao thì mô hình càng tốt trong việc giải thích biến thiên của dữ liệu đầu ra.

0.8899296029893499
94.07349931176896


In [ ]:

print(np.int16(Y_pred))
print(Y_test)
print('LN thu được là:',model.predict([[20,20,20]]))

[ 96 117 101  74  84  75 174 128 149]
[ 90 109 107  91  97  78 166 142 152]
LN thu được là: [79.2020648]


Tính MSE R2 rồi thì làm gì,
Có các intercept và coef thi có phải viết ra mô hình sau đó điền tham số vào để dự đoán hay không?
